### ISSUE TITLE
index reordering

### ISSUE THREAD

**Issue by lizhenstat** [Daniil-Osokin/fully-learnable-group-convolution.pytorch#6]
Hi, thanks for your work!

I have a question on "Index reordering" part,
Do you know how to implement this fast inference as stand group convolution?
(as the author states in paper)

Since it is group convolution with uneven input channel number.
I don't know how to achieve this.

Thanks

**Comment by Daniil-Osokin** [comment]
Hi! Index reordering just allows channels in the same group go sequentially, one by one (and same for filters, which work with the same group). It does not solve the problem with uneven channels (or filters) in groups. So none of standard layers can process it as is in an efficient way (we pointed out it in [implementation notes](https://github.com/Daniil-Osokin/fully-learnable-group-convolution.pytorch#implementation-notes)). My best guess, that authors have proprietary optimized implementation, which supports uneven channels in groups.

**Comment by lizhenstat** [comment]
Oh, thanks a lot, you've already mentioned it! 
I'll look the paper you reccommand
